# Generated by Django 4.2 on 2023-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_preview1_product_preview2_product_preview3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview10',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
