# Generated by Django 4.2 on 2023-05-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_countinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSize',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
