# Generated by Django 4.2 on 2023-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_order_createdat_alter_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
