# Generated by Django 4.2 on 2023-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_order_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimg',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview1',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview10',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview2',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview3',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview4',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview5',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview6',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview7',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview8',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview9',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSize',
            field=models.ImageField(blank=True, default='/pants4.jpg', null=True, upload_to=''),
        ),
    ]
