# Generated by Django 4.2 on 2023-07-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_shippingaddress_fname_shippingaddress_iname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='iName',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='oName',
        ),
    ]
