# Generated by Django 4.2 on 2023-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_fname_shippingaddress_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
